#!/bin/bash -eu


FW_CODE=/usr/share/edk2/ovmf/OVMF_CODE.cc.fd
FW_VARS_TEMPL=/usr/share/edk2/ovmf/OVMF_VARS.fd

while getopts ":w:c:v:" o; do
    case "${o}" in
        w)
            WORKSPACE="$(realpath "${OPTARG}")"
            test -d "${WORKSPACE}" || ( echo "WORKSPACE ${WORKSPACE} not found"; exit 1 )
            FW_CODE="${WORKSPACE}/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_CODE.fd"
            FW_VARS_TEMPL="${WORKSPACE}/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_VARS.fd"
            ;;
        c)
            FW_CODE="$(realpath "${OPTARG}")"
            test -f "${FW_CODE}" || ( echo "FW_CODE ${FW_CODE} not found"; exit 1 )
            ;;
        v)
            FW_VARS_TEMPL="$(realpath "${OPTARG}")"
            test -f "${FW_VARS_TEMPL}" || ( echo "FW_VARS_TEMPL ${FW_VARS_TEMPL} not found"; exit 1 )
            ;;
        *)
            usage
            ;;
    esac
done

shift $(( OPTIND - 1 ))

CMDLINE+=$*

echo "FW CODE: ${FW_CODE}"
echo "FW VARS: ${FW_VARS_TEMPL}"

FW_VARS=$(mktemp)
cp "${FW_VARS_TEMPL}" "${FW_VARS}"
trap "rm -f \${FW_VARS}" EXIT

/usr/bin/qemu-system-x86_64 \
    -machine q35 \
    -machine accel=kvm -m 1G -boot menu=on \
    -cpu max \
    -blockdev node-name=code,driver=file,filename="${FW_CODE}",read-only=on \
    -blockdev node-name=vars,driver=file,filename="${FW_VARS}" \
    -machine pflash0=code \
    -machine pflash1=vars \
    -chardev file,id=fw,path="firmware.log" \
    -device isa-debugcon,iobase=0x402,chardev=fw \
    -net none \
    $CMDLINE
